{
 "title": "Apache Flink Dashboard | HDI on AKS",
 "description": "Dashboard for Flink [HDI on AKS]",
 "tags": [
  "flink",
  "task manager",
  "job manager",
  "apache"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "query": "prometheus" },
   { "name": "clusterpool", "label": "ClusterPoolName", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "cluster",
    "label": "ClusterDeploymentID",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster=\"$clusterpool\"},namespace)"
    }
   },
   {
    "name": "jm_instance",
    "label": "Job Manager",
    "query": {
     "query": "label_values(flink_jobmanager_numRegisteredTaskManagers{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"},instance)"
    }
   },
   {
    "name": "tm_id",
    "label": "Task Manager",
    "query": {
     "query": "label_values(flink_taskmanager_Status_JVM_Threads_Count{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"},tm_id)"
    }
   },
   {
    "name": "job_name",
    "label": "Job Name",
    "query": {
     "query": "label_values(flink_jobmanager_job_uptime{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"},job_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Job Manager (JVM - CPU)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Load",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "flink_jobmanager_status_jvm_cpu_load{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "delta(flink_jobmanager_status_jvm_cpu_time{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}[5m])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_status_jvm_threads_count{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Manager (JVM - Memory Usage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Heap Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Heap_Used{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "NonHeap Used",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_NonHeap_Used{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Direct Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Direct_MemoryUsed{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mapped Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Mapped_MemoryUsed{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Metaspace Memory Used",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_Memory_Metaspace_Used{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Manager (JVM - Garbage Collector)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Mark Sweep Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_GarbageCollector_MarkSweepCompact_Time{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Mark Sweep Count",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_Status_JVM_GarbageCollector_MarkSweepCompact_Count{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Job Manager (Slots & Jobs)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Task Managers",
     "type": "stat",
     "gridPos": { "h": 8, "w": 3, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_numRegisteredTaskManagers{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Task Slots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 3, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_taskSlotsTotal{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Available Task Slots",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 7, "x": 10, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_taskSlotsAvailable{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Runnings Jobs",
     "type": "stat",
     "gridPos": { "h": 8, "w": 7, "x": 17, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_numRunningJobs{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job Restarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_numRestarts{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job FullRestarts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_fullRestarts{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\", job_name=\"$job_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job Restartine Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_restartingTime{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\",job_name=\"$job_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Job Uptime",
     "type": "stat",
     "gridPos": { "h": 10, "w": 21, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_uptime{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\",job_name=\"$job_name\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Uptime Derscription",
     "type": "text",
     "gridPos": { "h": 10, "w": 3, "x": 21, "y": 20 },
     "options": {
      "content": "# Uptime Description\n\n| Color | Status|\n|---|---|\n| Green | < 1 Hour |\n| Yellow | >= 1 Hour  |\n| Orange | >= 6 Hours |\n| Purple | >= 1 Day |\n| Red | >= 3 days |\n"
     },
     "targets": [
      {}
     ]
    }
   ]
  },
  { "title": "Job Manager (Checkpoints)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "flink_jobmanager_job_totalNumberOfCheckpoints{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\",job_name=\"$job_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Completed Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfCompletedCheckpoints{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\",job_name=\"$job_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In Progress Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfInProgressCheckpoints{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\",job_name=\"$job_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Checkpoints",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 5 },
   "targets": [
    {
     "expr": "flink_jobmanager_job_numberOfFailedCheckpoints{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\",job_name=\"$job_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Checkpoint Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointSize{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\",job_name=\"$job_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last Checkpoint Duration",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "flink_jobmanager_job_lastCheckpointDuration{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",instance=~\"$jm_instance\",job_name=\"$job_name\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Manager (JVM - CPU)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Load",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_CPU_Load{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "delta(flink_taskmanager_Status_JVM_CPU_Time{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}[5m])",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Threads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Threads_Count{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (JVM - Memory Usage)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Heap",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Heap_Used{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Non Heap",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_NonHeap_Used{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Direct",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Mapped",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Mapped_MemoryUsed{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Metaspace",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_Memory_Metaspace_Used{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (JVM - Garbage Collector)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Young Generation Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_GarbageCollector_G1_Young_Generation_Time{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Old Generation Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_JVM_GarbageCollector_G1_Old_Generation_Time{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Memory - Flink)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Memory Managed Used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "flink_taskmanager_status_flink_memory_managed_used{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Memory Managed Total",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "flink_taskmanager_status_flink_memory_managed_total{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Memory - Shuffle Netty)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Total Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_TotalMemory{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Total Memory Segments",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_TotalMemorySegments{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Used Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_UsedMemory{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Available Memory",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 6, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_AvailableMemory{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Used Memory Segments",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_UsedMemorySegments{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    },
    {
     "title": "Available Memory Segments",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 6, "x": 18, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "flink_taskmanager_Status_Shuffle_Netty_AvailableMemorySegments{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",tm_id=~\"${tm_id}\"}",
       "legendFormat": "{{tm_id}}"
      }
     ]
    }
   ]
  }
 ]
}