{
 "title": "Apache Kafka Dashboard | HDI on AKS",
 "tags": [
  "broker ",
  "kraft controller",
  "apache",
  "kafka"
 ],
 "time": { "from": "2024-02-01T11:05:19.641Z", "to": "2024-02-01T12:18:50.865Z" },
 "templating": {
  "list": [
   { "name": "Source", "query": "prometheus" },
   { "name": "clusterpool", "label": "ClusterPoolName", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "cluster_name",
    "label": "ClusterName",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_value{cluster=\"$clusterpool\"},hdinsightcluster)"
    }
   },
   {
    "name": "broker_name",
    "label": "Broker",
    "query": {
     "query": "label_values(kafka_server_kafkaserver_value{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",name=\"brokerstate\"},kubernetes_pod_name)"
    }
   },
   {
    "name": "controller_name",
    "label": "Controller",
    "query": {
     "query": "label_values(kafka_controller_kafkacontroller_value{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", name=\"activecontrollercount\"},kubernetes_pod_name)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",name=\"bytesinpersec\"},topic)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Cluster Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Broker State",
     "type": "timeseries",
     "description": "State of the Broker",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "kafka_server_kafkaserver_value{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"brokerstate\", kubernetes_pod_name=~\"$broker_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Active Controller Count",
     "type": "timeseries",
     "description": "Active Kraft Controller",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "kafka_controller_kafkacontroller_value{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"activecontrollercount\", kubernetes_pod_name=~\"$controller_name\"}",
       "legendFormat": "{{kubernetes_pod_name}}"
      }
     ]
    },
    {
     "title": "Active Broker Count",
     "type": "timeseries",
     "description": "Active Kraft Controller",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "max(kafka_controller_kafkacontroller_value{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"activebrokercount\"})",
       "legendFormat": "$cluster_name"
      }
     ]
    },
    {
     "title": "Global Topic Count",
     "type": "timeseries",
     "description": "Total number of topics",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "targets": [
      {
       "expr": "max(kafka_controller_kafkacontroller_value{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"globaltopiccount\"})",
       "legendFormat": "$cluster_name"
      }
     ]
    }
   ]
  },
  {
   "title": "Bytes In & Out /s | Messages In /s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Bytes In & Out across brokers /s",
     "type": "timeseries",
     "description": "Average bytes movement per cluster",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "avg(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"bytesinpersec\", kubernetes_pod_name=~\"$broker_name\"})",
       "legendFormat": "Bytes In /s ($cluster_name)"
      },
      {
       "expr": "avg(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"bytesoutpersec\", kubernetes_pod_name=~\"$broker_name\"})",
       "legendFormat": "Bytes Out /s ($cluster_name)"
      }
     ]
    },
    {
     "title": "Average Messages In across brokers /s",
     "type": "timeseries",
     "description": "Average messages across nodes in a cluster",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "avg(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"messagesinpersec\", kubernetes_pod_name=~\"$broker_name\"})",
       "legendFormat": "Messages In /s ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Bytes In & Out per cluster /s",
     "type": "timeseries",
     "description": "Total bytes movement per cluster",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"bytesinpersec\", kubernetes_pod_name=~\"$broker_name\"})",
       "legendFormat": "Bytes In /s ($cluster_name)"
      },
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"bytesoutpersec\", kubernetes_pod_name=~\"$broker_name\"})",
       "legendFormat": "Bytes Out /s ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Messages In across cluster /s",
     "type": "timeseries",
     "description": "Total messages across nodes in a cluster",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "targets": [
      {
       "expr": "sum(kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"messagesinpersec\", kubernetes_pod_name=~\"$broker_name\"})",
       "legendFormat": "Messages In /s ($cluster_name)"
      }
     ]
    },
    {
     "title": "Average Bytes In & Out across brokers /s",
     "type": "timeseries",
     "description": "Bytes movement per cluster",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "targets": [
      {
       "expr": "kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"bytesinpersec\", kubernetes_pod_name=~\"$broker_name\", topic!~\"$topic\"}",
       "legendFormat": "Bytes In /s {{kubernetes_pod_name}} ($cluster_name)"
      },
      {
       "expr": "kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"bytesoutpersec\", kubernetes_pod_name=~\"$broker_name\", topic!~\"$topic\"}",
       "legendFormat": "Bytes Out /s {{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Average Messages In across brokers /s",
     "type": "timeseries",
     "description": "Messages across nodes in a cluster",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "targets": [
      {
       "expr": "kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"messagesinpersec\", kubernetes_pod_name=~\"$broker_name\", topic!~\"$topic\"}",
       "legendFormat": "Messages In /s {{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Bytes In & Out per topic /s",
     "type": "timeseries",
     "description": "Bytes movement per topic",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "targets": [
      {
       "expr": "kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"bytesinpersec\", kubernetes_pod_name=~\"$broker_name\", topic=~\"$topic\"}",
       "legendFormat": "Bytes In /s Topic={{topic}} ($cluster_name)"
      },
      {
       "expr": "kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"bytesoutpersec\", kubernetes_pod_name=~\"$broker_name\", topic=~\"$topic\"}",
       "legendFormat": "Bytes Out /s Topic={{topic}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Messages In per topic /s",
     "type": "timeseries",
     "description": "Messages In per topic",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "targets": [
      {
       "expr": "kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"messagesinpersec\", kubernetes_pod_name=~\"$broker_name\", topic=~\"$topic\"}",
       "legendFormat": "Messages In /s Topic={{topic}} ($cluster_name)"
      }
     ]
    }
   ]
  },
  {
   "title": "Producer & Consumer Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Producer Requests /s",
     "type": "timeseries",
     "description": "Average producer requests across nodes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "avg(kafka_network_requestmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"requestspersec\", request=\"produce\"})",
       "legendFormat": "Average Producer Requests /s ($cluster_name)"
      }
     ]
    },
    {
     "title": "Average Consumer Requests /s",
     "type": "timeseries",
     "description": "Average consumer requests across nodes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "avg(kafka_network_requestmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"requestspersec\", request=\"fetchconsumer\"})",
       "legendFormat": "Average Consumer Requests /s ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Producer Requests /s",
     "type": "timeseries",
     "description": "Total producer requests across nodes",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(kafka_network_requestmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"requestspersec\", request=\"produce\"})",
       "legendFormat": "Total Producer Requests /s ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Consumer Requests /s",
     "type": "timeseries",
     "description": "Total consumer requests across nodes",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(kafka_network_requestmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"requestspersec\", request=\"fetchconsumer\"})",
       "legendFormat": "Total Consumer Requests /s ($cluster_name)"
      }
     ]
    },
    {
     "title": "Producer Requests per broker /s",
     "type": "timeseries",
     "description": "Producer requests per broker",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"requestspersec\", request=\"produce\"}",
       "legendFormat": "Producer Requests /s {{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Consumer Requests per broker /s",
     "type": "timeseries",
     "description": "Consumer requests per broker",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"requestspersec\", request=\"fetchconsumer\"}",
       "legendFormat": "Consumer Requests /s {{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Produce Requests per topic /s",
     "type": "timeseries",
     "description": "Total Produce requests per topic",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totalproducerequestspersec\", topic=~\"$topic\"}",
       "legendFormat": "Total Produce Requests /s Topic={{topic}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Fetch Requests per topic /s",
     "type": "timeseries",
     "description": "Total fetch requests per topic",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "kafka_server_brokertopicmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totalfetchrequestspersec\", topic=~\"$topic\"}",
       "legendFormat": "Total Fetch Requests /s Topic={{topic}} ($cluster_name)"
      }
     ]
    }
   ]
  },
  {
   "title": "Partition & Leader Information",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Partition Count",
     "type": "timeseries",
     "description": "Number of partitions in a pod",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_value{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"partitioncount\", kubernetes_pod_name=~\"$broker_name\"}",
       "legendFormat": "$cluster_name"
      }
     ]
    },
    {
     "title": "Leader Count",
     "type": "timeseries",
     "description": "Number of leaders in a pod",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_value{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"leadercount\", kubernetes_pod_name=~\"$broker_name\"}",
       "legendFormat": "$cluster_name"
      }
     ]
    },
    {
     "title": "Under Replicated Partitions",
     "type": "timeseries",
     "description": "Number of under replicated partitions in a pod",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_value{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"underreplicatedpartitions\", kubernetes_pod_name=~\"$broker_name\"}",
       "legendFormat": "$cluster_name"
      }
     ]
    },
    {
     "title": "Offline Partition Count",
     "type": "timeseries",
     "description": "Number of offline partitions per pod",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "targets": [
      {
       "expr": "kafka_controller_kafkacontroller_value{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"offlinepartitionscount\", kubernetes_pod_name=~\"$controller_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Offline Replica Count",
     "type": "timeseries",
     "description": "Number of offline replicas per pod",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_value{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"offlinereplicacount\", kubernetes_pod_name=~\"$broker_name\"}",
       "legendFormat": "$cluster_name"
      }
     ]
    }
   ]
  },
  {
   "title": "In-Sync Replica Shrinks / Expands",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average In-Sync Replica Shrinks /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "targets": [
      {
       "expr": "avg(kafka_server_replicamanager_count{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"isrshrinkspersec\", kubernetes_pod_name=~\"$broker_name\"})",
       "legendFormat": "$cluster_name"
      }
     ]
    },
    {
     "title": "Average In-Sync Replica Expands /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "targets": [
      {
       "expr": "avg(kafka_server_replicamanager_count{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"isrexpandspersec\", kubernetes_pod_name=~\"$broker_name\"})",
       "legendFormat": "$cluster_name"
      }
     ]
    },
    {
     "title": "In-Sync Replica Shrinks /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_count{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"isrshrinkspersec\", kubernetes_pod_name=~\"$broker_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "In-Sync Replica Expands /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "targets": [
      {
       "expr": "kafka_server_replicamanager_count{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"isrexpandspersec\", kubernetes_pod_name=~\"$broker_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    }
   ]
  },
  {
   "title": "Replica Fetcher Manager and Consumer Lag",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Replica Fetcher Manager MaxLag",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "expr": "kafka_server_replicafetchermanager_value{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"maxlag\", kubernetes_pod_name=~\"$broker_name\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Consumer Lag per topic",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "kafka_server_fetcherlagmetrics_value{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", name=\"consumerlag\", kubernetes_pod_name=~\"$broker_name\", partition=\"0\", topic=~\"$topic\"}",
       "legendFormat": "{{topic}} ($cluster_name)"
      }
     ]
    }
   ]
  },
  {
   "title": "Fetch Consumer Total Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch Consumer Requests /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", request=\"fetchconsumer\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Time Ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_count{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"fetchconsumer\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Time Ms (min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_min{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"fetchconsumer\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Time Ms (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_max{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"fetchconsumer\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Time Ms (mean)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_mean{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"fetchconsumer\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Time Ms (99th Percentile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_99thpercentile{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"fetchconsumer\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    }
   ]
  },
  {
   "title": "Fetch Follower Total Time",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "Fetch Follower Requests /s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", request=\"fetchfollower\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Time Ms",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_count{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"fetchfollower\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Time Ms (min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_min{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"fetchfollower\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Time Ms (max)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_max{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"fetchfollower\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Time Ms (mean)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_mean{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"fetchfollower\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    },
    {
     "title": "Total Time Ms (99th Percentile)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "kafka_network_requestmetrics_99thpercentile{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"fetchfollower\"}",
       "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
      }
     ]
    }
   ]
  },
  { "title": "Produce Total Time", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Produce Requests /s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_oneminuterate{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", request=\"produce\"}",
     "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
    }
   ]
  },
  {
   "title": "Total Time Ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_count{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"produce\"}",
     "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
    }
   ]
  },
  {
   "title": "Total Time Ms (min)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_min{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"produce\"}",
     "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
    }
   ]
  },
  {
   "title": "Total Time Ms (max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_max{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"produce\"}",
     "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
    }
   ]
  },
  {
   "title": "Total Time Ms (mean)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_mean{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"produce\"}",
     "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
    }
   ]
  },
  {
   "title": "Total Time Ms (99th Percentile)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "targets": [
    {
     "expr": "kafka_network_requestmetrics_99thpercentile{cluster=\"$clusterpool\", hdinsightcluster=\"$cluster_name\", kubernetes_pod_name=~\"$broker_name\", name=\"totaltimems\", request=\"produce\"}",
     "legendFormat": "{{kubernetes_pod_name}} ($cluster_name)"
    }
   ]
  }
 ]
}