{
 "title": "Apache Spark Dashboard | HDI on AKS",
 "description": "Dashboard for Spark [HDI on AKS]",
 "tags": [
  "spark",
  "executor",
  "driver",
  "apache"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Source", "query": "prometheus" },
   { "name": "clusterpool", "label": "ClusterPoolName", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "cluster",
    "label": "ClusterDeploymentID",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster=\"$clusterpool\"},namespace)"
    }
   },
   {
    "name": "nodemanager",
    "label": "Nodemanager Node",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$cluster\"},pod)"
    }
   },
   {
    "name": "resourcemanager",
    "label": "ResourceManager Node",
    "query": {
     "query": "label_values(kube_pod_labels{namespace=\"$cluster\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "ResourceManager Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Number of Active Applications",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_activeapplications{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", q0=\"root\", q1=\"spark\", name=\"queuemetrics\", kubernetes_pod_name=~\"$resourcemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Allocated And Available Memory",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_allocatedmb{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", q0=\"root\", q1=\"spark\", name=\"queuemetrics\", kubernetes_pod_name=~\"$resourcemanager\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hadoop_resourcemanager_availablemb{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", q0=\"root\", q1=\"spark\", name=\"queuemetrics\", kubernetes_pod_name=~\"$resourcemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total Available and Allocated Vcores",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_availablevcores{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", q0=\"root\", q1=\"spark\", name=\"queuemetrics\", kubernetes_pod_name=~\"$resourcemanager\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hadoop_resourcemanager_allocatedvcores{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", q0=\"root\", q1=\"spark\", name=\"queuemetrics\", kubernetes_pod_name=~\"$resourcemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Running Apps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_appsrunning{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", q0=\"root\", q1=\"spark\", name=\"queuemetrics\", kubernetes_pod_name=~\"$resourcemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Pending Apps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_appspending{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", q0=\"root\", q1=\"spark\", name=\"queuemetrics\", kubernetes_pod_name=~\"$resourcemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Submitted Apps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_appssubmitted{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", q0=\"root\", q1=\"spark\", name=\"queuemetrics\", kubernetes_pod_name=~\"$resourcemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Failed Apps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_appsfailed{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", q0=\"root\", q1=\"spark\", name=\"queuemetrics\", kubernetes_pod_name=~\"$resourcemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Apps Killed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 13 },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_appskilled{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", q0=\"root\", q1=\"spark\", name=\"queuemetrics\", kubernetes_pod_name=~\"$resourcemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Completed Apps",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_appscompleted{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", q0=\"root\", q1=\"spark\", name=\"queuemetrics\", kubernetes_pod_name=~\"$resourcemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Active NMs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_numactivenms{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total number of Allocated Containers ",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_allocatedcontainers{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", q0=\"root\", q1=\"spark\", name=\"queuemetrics\", kubernetes_pod_name=~\"$resourcemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Decommissiong NMs",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 19 },
   "targets": [
    {
     "expr": "hadoop_resourcemanager_numdecommissioningnms{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$resourcemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor Nodemanager Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Executor Node: Memory Allocated And Available",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "hadoop_nodemanager_allocatedgb{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hadoop_nodemanager_availablegb{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor Node: Available and Allocated Vcores",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 26 },
   "targets": [
    {
     "expr": "hadoop_nodemanager_availablevcores{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hadoop_nodemanager_allocatedvcores{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$nodemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor Node: Container Metrics",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "targets": [
    {
     "expr": "hadoop_nodemanager_containersrunning{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hadoop_nodemanager_containerscompleted{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hadoop_nodemanager_containersfailed{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor Node: Allocated Containers",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "hadoop_nodemanager_allocatedcontainers{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executor Node: GC Count and TimeMilliSec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 7, "y": 33 },
   "targets": [
    {
     "expr": "hadoop_nodemanager_gccount{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "hadoop_nodemanager_gctimemillis{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$nodemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Registered Executor 99th Percentile Latency",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "targets": [
    {
     "expr": "hadoop_nodemanager_registerexecutorrequestlatencymillis_999thpercentile{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Threads & Memory Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Jvm Heap Used and Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_heapmemoryusage_used{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "java_lang_memory_heapmemoryusage_max{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$nodemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jvm Non Heap Used and Max",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_memory_nonheapmemoryusage_used{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "java_lang_memory_nonheapmemoryusage_max{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=\"$nodemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Threads Current And Deadlocked",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_threads_deadlocked{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jvm Process CPU Time and Load",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "java_lang_operatingsystem_processcputime{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "java_lang_operatingsystem_processcpuload{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Jvm GC count and time",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_sum{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM total classes loaded",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "jvm_classes_loaded_total{cluster=\"$clusterpool\", kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"$nodemanager\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 61 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Executor Network Transmitted",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_network_transmit_bytes_total{cluster=\"$clusterpool\", namespace=\"$cluster\", pod=~\"$nodemanager\"}",
     "legendFormat": "{{ pod_name }} {{kubernetes_io_hostname}} Transmitted"
    }
   ]
  },
  {
   "title": "Executor Network Received",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 62 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "container_network_receive_bytes_total{cluster=\"$clusterpool\", namespace=\"$cluster\", pod=~\"$nodemanager\"}",
     "legendFormat": "{{ pod_name }} {{kubernetes_io_hostname}}  Received"
    }
   ]
  },
  {
   "title": "Disk IO",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 70 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Disk Read Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 71 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_reads_bytes_total{cluster=\"$clusterpool\", namespace=\"$cluster\", pod=~\"$nodemanager\"}",
     "legendFormat": "{{pod_name }} {{device}} Read"
    }
   ]
  },
  {
   "title": "Disk Writes Bytes",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 71 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "container_fs_writes_bytes_total{cluster=\"$clusterpool\", namespace=\"$cluster\", pod=~\"$nodemanager\"}",
     "legendFormat": "{{pod_name }}{{device}} Write"
    }
   ]
  }
 ]
}