{
 "title": "Trino Dashboard | HDI on AKS",
 "description": "Dashboard for Trino [HDI on AKS]",
 "tags": [ "trino" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Source", "query": "prometheus" },
   { "name": "clusterpool", "label": "ClusterPoolName", "query": { "query": "label_values(up,cluster)" } },
   {
    "name": "cluster",
    "label": "ClusterDeploymentID",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster=\"$clusterpool\"},namespace)"
    }
   },
   {
    "name": "activeCoordinatorPodName",
    "label": "Active coordinator",
    "query": {
     "query": "query_result(trino_execution_querymanager_submittedqueries_totalcount{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"} > 0)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trino_execution_querymanager_runningqueries{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$activeCoordinatorPodName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queued queries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trino_execution_querymanager_queuedqueries{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$activeCoordinatorPodName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reserved memory",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trino_memory_clustermemorymanager_clusterusermemoryreservation{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$activeCoordinatorPodName\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "trino_memory_clustermemorymanager_clusterusermemoryreservation{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$activeCoordinatorPodName\"} / trino_memory_clustermemorymanager_clustermemorybytes{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$activeCoordinatorPodName\"} * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$cluster\", pod=~\"trino-worker-*\", cluster=\"$clusterpool\"}) / sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$clusterpool\", namespace=\"$cluster\", pod=~\"trino-worker-*\", resource=\"cpu\"}) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total bytes from cache",
   "type": "stat",
   "description": "Cumulative amount of data read from final result cache (disk).",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "trino_cache_cachestats_totalbytesfromcache{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$activeCoordinatorPodName\"}",
     "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Cluster information",
   "type": "text",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "options": {
    "content": "|Coordinator|\r\n|-----------|\r\n|${activeCoordinatorPodName}|"
   },
   "targets": [
    { "panelId": 162 }
   ]
  },
  {
   "title": "Query rate (over 5 minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "trino_execution_querymanager_completedqueries_fiveminute_rate{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Completed"
    },
    {
     "expr": "trino_execution_querymanager_submittedqueries_fiveminute_rate{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Submitted"
    },
    {
     "expr": "trino_execution_querymanager_failedqueries_fiveminute_rate{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "CPU Usage Workers (cores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$cluster\", pod=~\"trino-worker-*\", cluster=\"$clusterpool\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(kube_pod_container_resource_limits{job=\"kube-state-metrics\", cluster=\"$clusterpool\", namespace=\"$cluster\", pod=~\"trino-worker-*\", resource=\"cpu\"})\r\n",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Failures rate (over 5 minutes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "trino_execution_querymanager_usererrorfailures_fiveminute_rate{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "User"
    },
    {
     "expr": "trino_execution_querymanager_externalfailures_fiveminute_rate{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "External"
    },
    {
     "expr": "trino_execution_querymanager_insufficientresourcesfailures_fiveminute_rate{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Insufficient resources"
    },
    {
     "expr": "trino_execution_querymanager_internalfailures_fiveminute_rate{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Internal"
    },
    {
     "expr": "trino_execution_querymanager_failedqueries_fiveminute_rate{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Memory usage %",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "trino_memory_clustermemorymanager_clusterusermemoryreservation{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$activeCoordinatorPodName\"} / trino_memory_clustermemorymanager_clustermemorybytes{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=\"$activeCoordinatorPodName\"} * 100",
     "legendFormat": "Memory usage"
    }
   ]
  },
  {
   "title": "Query count total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trino_execution_querymanager_failedqueries_totalcount{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Completed"
    },
    {
     "expr": "trino_execution_querymanager_submittedqueries_totalcount{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Submitted"
    },
    {
     "expr": "trino_execution_querymanager_failedqueries_totalcount{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Failed"
    }
   ]
  },
  {
   "title": "Input Bytes/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "trino_execution_querymanager_consumedinputbytes_oneminute_rate{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Input bytes/sec"
    }
   ]
  },
  {
   "title": "Failures count total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "trino_execution_querymanager_usererrorfailures_totalcount{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "User"
    },
    {
     "expr": "trino_execution_querymanager_externalfailures_totalcount{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "External"
    },
    {
     "expr": "trino_execution_querymanager_insufficientresourcesfailures_totalcount{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Insufficient resources"
    },
    {
     "expr": "trino_execution_querymanager_internalfailures_totalcount{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Internal"
    },
    {
     "expr": "trino_execution_querymanager_failedqueries_totalcount{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Input Rows/sec",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "trino_execution_querymanager_consumedinputrows_oneminute_rate{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "Input rows/sec"
    }
   ]
  },
  {
   "title": "Execution time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "trino_execution_querymanager_executiontime_alltime_p99{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "P99"
    },
    {
     "expr": "trino_execution_querymanager_executiontime_alltime_p95{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "P95"
    }
   ]
  },
  {
   "title": "Queued time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "trino_execution_querymanager_queuedtime_alltime_p95{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "P95"
    },
    {
     "expr": "trino_execution_querymanager_queuedtime_alltime_p99{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Result cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 } },
  {
   "title": "Space used",
   "type": "timeseries",
   "description": "Disk space used by final result cache",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "trino_cache_cachestats_spaceused{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
    }
   ]
  },
  {
   "title": "Cache hit rate",
   "type": "timeseries",
   "description": "Final result cache hit rate",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
   "targets": [
    {
     "expr": "trino_cache_cachestats_hitrate{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\"}",
     "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
    }
   ]
  },
  {
   "title": "JVM - CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Coordinator load",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "java_lang_operatingsystem_cpuload{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"trino-coordinator*\"}",
       "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Worker load",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "java_lang_operatingsystem_cpuload{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\", kubernetes_pod_name=~\"trino-worker*\"}",
       "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Coordinator Threads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "java_lang_threading_threadcount{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=~\"trino-coordinator*\"}",
       "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Worker Threads",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "java_lang_threading_threadcount{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=~\"trino-worker*\"}",
       "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - Memory Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Coordinator Heap Used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "java_lang_memory_heapmemoryusage_used{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=~\"trino-coordinator*\"}",
       "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Worker Heap Used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "java_lang_memory_heapmemoryusage_used{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=~\"trino-worker*\"}",
       "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Coordinator Non-Heap Used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "java_lang_memory_nonheapmemoryusage_used{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=~\"trino-coordinator*\"}",
       "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Worker Non-Heap Used",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "java_lang_memory_nonheapmemoryusage_used{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=~\"trino-worker*\"}",
       "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM - Garbage Collector",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Coordinator Young Generation Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "java_lang_g1_young_generation_collectiontime{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=~\"trino-coordinator*\"}",
       "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Worker Young Generation Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "java_lang_g1_young_generation_collectiontime{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=~\"trino-worker*\"}",
       "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Coordinator Old Generation Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "java_lang_g1_old_generation_collectiontime{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=~\"trino-coordinator*\"}",
       "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
      }
     ]
    },
    {
     "title": "Worker Old Generation Time",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "java_lang_g1_old_generation_collectiontime{cluster=\"$clusterpool\",kubernetes_namespace=\"$cluster\",kubernetes_pod_name=~\"trino-worker*\"}",
       "legendFormat": "{{kubernetes_pod_name}}/{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}